import { ScheduleType } from "../models/Schedule";

const mockSchedule = [
  {
    type: ScheduleType.WEEKLY,
    condition: "sunday",
    value: "10:00",
    period: "36.5",
    activeRelay: [1, 2],
    deviceId: 1,
  },
  {
    type: ScheduleType.SENSOR,
    condition: "Device 1",
    value: "37.4",
    period: "60",
    activeRelay: [1, 2],
    deviceId: 1,
  },
  {
    type: ScheduleType.WEEKLY,
    condition: "monday",
    value: "11:00",
    period: "37.3",
    activeRelay: [2, 3],
    deviceId: 2,
  },
  {
    type: ScheduleType.SENSOR,
    condition: "Device 2",
    value: "33.6",
    period: "60",
    activeRelay: [2, 3],
    deviceId: 2,
  },
  {
    type: ScheduleType.WEEKLY,
    condition: "tuesday",
    value: "09:00",
    period: "37.4",
    activeRelay: [3, 4],
    deviceId: 3,
  },
  {
    type: ScheduleType.SENSOR,
    condition: "Device 3",
    value: "35.4",
    period: "60",
    activeRelay: [3, 4],
    deviceId: 3,
  },
  {
    type: ScheduleType.WEEKLY,
    condition: "wednesday",
    value: "15:00",
    period: "36.3",
    activeRelay: [4, 1],
    deviceId: 4,
  },
  {
    type: ScheduleType.SENSOR,
    condition: "Device 4",
    value: "34.2",
    period: "60",
    activeRelay: [4, 1],
    deviceId: 4,
  },
  {
    type: ScheduleType.WEEKLY,
    condition: "thursday",
    value: "17:00",
    period: "32.4",
    activeRelay: [1,2,3],
    deviceId: 1,
  },
  {
    type: ScheduleType.SENSOR,
    condition: "Device 1",
    value: "34.2",
    period: "60",
    activeRelay: [1,2,3],
    deviceId: 1,
  },
  {
    type: ScheduleType.WEEKLY,
    condition: "friday",
    value: "14:07",
    period: "33.7",
    activeRelay: [1,2,3,4],
    deviceId: 2,
  },
  {
    type: ScheduleType.SENSOR,
    condition: "Device 2",
    value: "37.3",
    period: "60",
    activeRelay: [11,2,3,4],
    deviceId: 2,
  },

];

export default mockSchedule;