version: "3"

services:
  # Database
  db:
    image: postgres
    ports:
      - 5432:5432
    container_name: database
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
    networks:
      - backend_network
    volumes:
      - postgres:/data/db
  # Backend server
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 3080:3080
    container_name: api
    networks:
      - backend_network
      - frontend_network
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: db
    volumes:
      - ./api/src:/usr/app/src
    depends_on:
      - db
  # Frontend server
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    container_name: ui
    networks:
      - frontend_network
    volumes:
      - ./ui/src:/usr/app/src
      - ./ui/public:/usr/app/public
    depends_on:
      - api
    stdin_open: true
    tty: true
    environment:
      REACT_APP_API_URL: http://api:3080

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge

volumes:
  postgres:
    driver: local
